# Generated by Django 6.0 on 2026-01-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='name',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(default='u', max_length=50),
        ),
    ]
