# Generated by Django 6.0 on 2026-01-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_server', '0002_remove_vehicle_description_remove_vehicle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(default='utility', max_length=50),
        ),
    ]
