# Generated by Django 6.0 on 2026-01-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_server', '0003_alter_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_id',
            field=models.IntegerField(auto_created=True, unique=True),
        ),
    ]
