# Generated by Django 6.0 on 2026-01-08 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_server', '0004_alter_vehicle_vehicle_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_id',
        ),
    ]
